network:
  version: 2
  renderer: networkd
  ethernets:
    ens32:                # Your interface name (check with 'ip a')
      dhcp4: no
      addresses:
        - 192.168.111.129/24 # Static IP and Subnet mask
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
      routes:
        - to: default
          via: 192.168.111.2 # Gateway IP
